<?php

namespace App\Filament\Resources\DocumentHistory\Tables;

use App\Models\GeneratedDocument;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Tables\Actions\BulkActionGroup;
use Filament\Tables\Actions\DeleteBulkAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class DocumentHistoryTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('document_type')
                    ->label('Document Type')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'rfq' => 'info',
                        'supplier_quote' => 'warning',
                        'purchase_order' => 'success',
                        'proforma_invoice' => 'primary',
                        'commercial_invoice' => 'danger',
                        default => 'gray',
                    })
                    ->formatStateUsing(fn (string $state): string => match ($state) {
                        'rfq' => 'RFQ',
                        'supplier_quote' => 'Supplier Quote',
                        'purchase_order' => 'Purchase Order',
                        'proforma_invoice' => 'Proforma Invoice',
                        'commercial_invoice' => 'Commercial Invoice',
                        default => strtoupper(str_replace('_', ' ', $state)),
                    })
                    ->searchable()
                    ->sortable(),
                
                TextColumn::make('document_number')
                    ->label('Document #')
                    ->searchable()
                    ->sortable()
                    ->copyable()
                    ->copyMessage('Document number copied')
                    ->placeholder('N/A'),
                
                TextColumn::make('format')
                    ->label('Format')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'pdf' => 'danger',
                        'excel' => 'success',
                        default => 'gray',
                    })
                    ->formatStateUsing(fn (string $state): string => strtoupper($state))
                    ->sortable(),
                
                TextColumn::make('filename')
                    ->label('Filename')
                    ->searchable()
                    ->limit(40)
                    ->tooltip(function (TextColumn $column): ?string {
                        $state = $column->getState();
                        if (strlen($state) > 40) {
                            return $state;
                        }
                        return null;
                    }),
                
                TextColumn::make('version')
                    ->label('Version')
                    ->sortable()
                    ->alignCenter(),
                
                TextColumn::make('revision_number')
                    ->label('Revision')
                    ->sortable()
                    ->alignCenter()
                    ->placeholder('N/A'),
                
                TextColumn::make('file_size')
                    ->label('Size')
                    ->formatStateUsing(fn (GeneratedDocument $record): string => $record->getFormattedSize())
                    ->sortable()
                    ->alignEnd(),
                
                TextColumn::make('generatedBy.name')
                    ->label('Generated By')
                    ->searchable()
                    ->sortable()
                    ->placeholder('System'),
                
                TextColumn::make('generated_at')
                    ->label('Generated At')
                    ->dateTime('Y-m-d H:i:s')
                    ->sortable()
                    ->since()
                    ->tooltip(fn (GeneratedDocument $record): string => $record->generated_at->format('Y-m-d H:i:s')),
                
                TextColumn::make('documentable_type')
                    ->label('Related To')
                    ->formatStateUsing(fn (string $state): string => class_basename($state))
                    ->searchable()
                    ->toggleable(isToggledHiddenByDefault: true),
                
                TextColumn::make('documentable_id')
                    ->label('Related ID')
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                
                TextColumn::make('generated_from_ip')
                    ->label('IP Address')
                    ->searchable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                SelectFilter::make('document_type')
                    ->label('Document Type')
                    ->options([
                        'rfq' => 'RFQ',
                        'supplier_quote' => 'Supplier Quote',
                        'purchase_order' => 'Purchase Order',
                        'proforma_invoice' => 'Proforma Invoice',
                        'commercial_invoice' => 'Commercial Invoice',
                    ])
                    ->multiple(),
                
                SelectFilter::make('format')
                    ->label('Format')
                    ->options([
                        'pdf' => 'PDF',
                        'excel' => 'Excel',
                    ])
                    ->multiple(),
                
                SelectFilter::make('generated_by')
                    ->label('Generated By')
                    ->relationship('generatedBy', 'name')
                    ->searchable()
                    ->preload(),
                
                Filter::make('generated_at')
                    ->form([
                        \Filament\Forms\Components\DatePicker::make('generated_from')
                            ->label('Generated From'),
                        \Filament\Forms\Components\DatePicker::make('generated_until')
                            ->label('Generated Until'),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        return $query
                            ->when(
                                $data['generated_from'],
                                fn (Builder $query, $date): Builder => $query->whereDate('generated_at', '>=', $date),
                            )
                            ->when(
                                $data['generated_until'],
                                fn (Builder $query, $date): Builder => $query->whereDate('generated_at', '<=', $date),
                            );
                    })
                    ->indicateUsing(function (array $data): array {
                        $indicators = [];
                        if ($data['generated_from'] ?? null) {
                            $indicators[] = 'From: ' . \Carbon\Carbon::parse($data['generated_from'])->toFormattedDateString();
                        }
                        if ($data['generated_until'] ?? null) {
                            $indicators[] = 'Until: ' . \Carbon\Carbon::parse($data['generated_until'])->toFormattedDateString();
                        }
                        return $indicators;
                    }),
            ])
            ->recordActions([
                Action::make('download')
                    ->label('Download')
                    ->icon('heroicon-o-arrow-down-tray')
                    ->color('success')
                    ->action(function (GeneratedDocument $record) {
                        if (!$record->exists()) {
                            Notification::make()
                                ->danger()
                                ->title('File not found')
                                ->body('The document file no longer exists on the server.')
                                ->send();
                            return;
                        }
                        
                        return response()->download(
                            $record->getFullPath(),
                            $record->filename
                        );
                    }),
                
                Action::make('view_related')
                    ->label('View Related')
                    ->icon('heroicon-o-arrow-top-right-on-square')
                    ->color('primary')
                    ->url(function (GeneratedDocument $record): ?string {
                        $type = $record->documentable_type;
                        $id = $record->documentable_id;
                        
                        // Map model types to Filament resource routes
                        $routeMap = [
                            'App\\Models\\Order' => 'orders',
                            'App\\Models\\SupplierQuote' => 'supplier-quotes',
                            'App\\Models\\PurchaseOrder' => 'purchase-orders',
                            'App\\Models\\ProformaInvoice' => 'proforma-invoices',
                            'App\\Models\\SalesInvoice' => 'sales-invoices',
                        ];
                        
                        $resourceName = $routeMap[$type] ?? null;
                        
                        if (!$resourceName) {
                            return null;
                        }
                        
                        return route("filament.panel.resources.{$resourceName}.edit", ['record' => $id]);
                    })
                    ->openUrlInNewTab()
                    ->visible(fn (GeneratedDocument $record): bool => $record->documentable_id !== null),
                
                \Filament\Tables\Actions\DeleteAction::make()
                    ->label('Delete')
                    ->requiresConfirmation()
                    ->modalHeading('Delete Document')
                    ->modalDescription('Are you sure you want to delete this document? The file will be permanently removed from the server.')
                    ->modalSubmitActionLabel('Yes, delete it'),
            ])
            ->bulkActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make()
                        ->requiresConfirmation()
                        ->modalHeading('Delete Documents')
                        ->modalDescription('Are you sure you want to delete the selected documents? The files will be permanently removed from the server.')
                        ->modalSubmitActionLabel('Yes, delete them'),
                ]),
            ])
            ->defaultSort('generated_at', 'desc')
            ->poll('30s')
            ->striped()
            ->paginated([10, 25, 50, 100]);
    }
}
