<?php

namespace App\Filament\Widgets;

use App\Models\GeneratedDocument;
use App\Repositories\DocumentRepository;
use Filament\Actions\DeleteAction;
use Filament\Notifications\Notification;
use Filament\Tables;
use Filament\Actions\Action;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Filament\Widgets\TableWidget as BaseWidget;
use Illuminate\Database\Eloquent\Model;

class RelatedDocumentsWidget extends BaseWidget
{
    public ?Model $record = null;

    protected int | string | array $columnSpan = 'full';

    protected static ?int $sort = 99;

    protected function getRepository(): DocumentRepository
    {
        return app(DocumentRepository::class);
    }

    public function table(Table $table): Table
    {
        return $table
            ->heading('Generated Documents History')
            ->description('All PDF and Excel documents generated for this record')
            ->query(
                $this->getRepository()->getTransactableDocumentsQuery(
                    get_class($this->record),
                    $this->record->id
                )
            )
            ->columns([
                TextColumn::make('document_type')
                    ->label('Type')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'rfq' => 'info',
                        'supplier_quote' => 'warning',
                        'purchase_order' => 'success',
                        'proforma_invoice' => 'primary',
                        'commercial_invoice' => 'danger',
                        default => 'gray',
                    })
                    ->formatStateUsing(fn (string $state): string => match ($state) {
                        'rfq' => 'RFQ',
                        'supplier_quote' => 'Supplier Quote',
                        'purchase_order' => 'Purchase Order',
                        'proforma_invoice' => 'Proforma Invoice',
                        'commercial_invoice' => 'Commercial Invoice',
                        default => strtoupper(str_replace('_', ' ', $state)),
                    }),
                
                TextColumn::make('format')
                    ->label('Format')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'pdf' => 'danger',
                        'excel' => 'success',
                        default => 'gray',
                    })
                    ->formatStateUsing(fn (string $state): string => strtoupper($state)),
                
                TextColumn::make('filename')
                    ->label('Filename')
                    ->limit(50)
                    ->tooltip(function (TextColumn $column): ?string {
                        $state = $column->getState();
                        if (strlen($state) > 50) {
                            return $state;
                        }
                        return null;
                    }),
                
                TextColumn::make('version')
                    ->label('Ver.')
                    ->alignCenter()
                    ->badge()
                    ->color('info'),
                
                TextColumn::make('revision_number')
                    ->label('Rev.')
                    ->alignCenter()
                    ->badge()
                    ->color('warning')
                    ->placeholder('N/A'),
                
                TextColumn::make('file_size')
                    ->label('Size')
                    ->formatStateUsing(fn (GeneratedDocument $record): string => $record->getFormattedSize())
                    ->alignEnd(),
                
                TextColumn::make('uploader.name')
                    ->label('Generated By')
                    ->placeholder('System')
                    ->icon('heroicon-o-user'),
                
                TextColumn::make('created_at')
                    ->label('Generated At')
                    ->dateTime('Y-m-d H:i')
                    ->since()
                    ->tooltip(fn (GeneratedDocument $record): string => $record->created_at->format('Y-m-d H:i:s')),
            ])
            ->actions([
                Action::make('download')
                    ->label('Download')
                    ->icon('heroicon-o-arrow-down-tray')
                    ->color('success')
                    ->button()
                    ->action(function (GeneratedDocument $record) {
                        if (!$record->exists()) {
                            Notification::make()
                                ->danger()
                                ->title('File not found')
                                ->body('The document file no longer exists on the server.')
                                ->send();
                            return;
                        }
                        
                        return response()->download(
                            $record->getFullPath(),
                            $record->filename
                        );
                    }),
                
                DeleteAction::make()
                    ->label('Delete')
                    ->requiresConfirmation()
                    ->modalHeading('Delete Document')
                    ->modalDescription('Are you sure you want to delete this document? The file will be permanently removed from the server.')
                    ->modalSubmitActionLabel('Yes, delete it')
                    ->action(function (GeneratedDocument $record) {
                        try {
                            $this->getRepository()->delete($record->id);
                            
                            Notification::make()
                                ->title('Document deleted successfully')
                                ->success()
                                ->send();
                        } catch (\Exception $e) {
                            Notification::make()
                                ->title('Error deleting document')
                                ->danger()
                                ->body($e->getMessage())
                                ->send();

                            \Log::error('Erro ao deletar documento', [
                                'id' => $record->id,
                                'error' => $e->getMessage(),
                            ]);
                        }
                    }),
            ])
            ->paginated([5, 10, 25])
            ->defaultPaginationPageOption(5)
            ->poll('30s')
            ->striped();
    }

    public static function canView(): bool
    {
        return true;
    }
}
